---
title: "Clustering"
author: "Helene Jordan"
date: "24/8/2021"
output: html_document
---

```{r, results=hide}
# devtools::install_github('charlie86/spotifyr')
library('spotifyr')
library(purrr)
library(lubridate)
library(knitr)
library(plyr)
library(ggplot2)
library(tidyr)
require(sqldf)
library(stringr)
library(dplyr)
library(googlesheets4)
library(stats)
library(factoextra)

library(datasets)
library(scales)
library(utf8)
library(utils)

library(graphics)
library(cluster)
```


```{r}
id <- 'a498307d278a4569a85f21de1f78d5d7'
secret <- '331e4c3def7c4b7a97a0e10e1901cfa9'
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
authorization_token <- get_spotify_authorization_code()
```



```{r}
songs <- read.csv('test_playlist.csv', header = TRUE, sep = ',')
```


```{r}
d <- daisy(songs) 
resultados <- rep(0, 10)
for (i in c(2,3,4,5,6,7,8,9,10))
{
  fit           <- kmeans(songs, i)
  y_cluster     <- fit$cluster
  sk            <- silhouette(y_cluster, d)
  resultados[i] <- mean(sk[,3])
}

plot(2:10,resultados[2:10],type="o",col="blue",pch=0,xlab="Numbero de clusters",ylab="Silueta")
```

```{r}
library(fpc)
fit_ch  <- kmeansruns(songs, krange = 1:10, criterion = "ch") 
fit_ch$bestk
```

```{r}
plot(1:10,fit_ch$crit,type="o",col="blue",pch=0,xlab="Número de clústers",ylab="Criterio Calinski-Harabasz")
```

```{r}
# Compute k-means with k = 4
set.seed(123)
km.res <- kmeans(songs, 8, nstart = 25)
```

```{r}
print(km.res)
```

```{r}
aggregate(songs, by=list(cluster=km.res$cluster), mean)
```

```{r}
dd <- cbind(songs, cluster = km.res$cluster)
head(dd)
```

