---
title: "Clustering"
author: "Helene Jordan"
date: "24/8/2021"
output: html_document
---

```{r, results=hide}
# devtools::install_github('charlie86/spotifyr')
library('spotifyr')
library(purrr)
library(lubridate)
library(knitr)
library(plyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(dplyr)
library(stats)
library(factoextra)

library(datasets)
library(scales)
library(utf8)
library(utils)

library(graphics)
library(cluster)
```


```{r}
id <- 'a498307d278a4569a85f21de1f78d5d7'
secret <- '331e4c3def7c4b7a97a0e10e1901cfa9'
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
authorization_token <- get_spotify_authorization_code()
```


```{r}
songs <- read.csv('../data/raw/song_features.csv', header = TRUE, sep = ',')
```

```{r}
quantitative_variables_songs <- songs %>%
  select(initial_user, danceability, energy, speechiness, acousticness, instrumentalness, liveness, valence, track.id)
quantitative_variables_songs <- quantitative_variables_songs[complete.cases(quantitative_variables_songs), ] 
```


```{r}
# Compute k-means with k = 10
set.seed(123)
km.res <- kmeans(quantitative_variables_songs[,c(2:8)], 10, nstart = 25)
```

```{r}
aggregate(quantitative_variables_songs[,c(2:8)], by=list(cluster=km.res$cluster), mean)
```

```{r}
clustered_songs <- cbind(quantitative_variables_songs, cluster = km.res$cluster)
head(clustered_songs)
```

```{r}
df <- data.frame(table(clustered_songs$cluster,clustered_songs$initial_user))
table(clustered_songs$cluster)
```


```{r}
df <- group_by(df, Var1) %>% 
  mutate(percent = Freq/sum(Freq)) %>%
  mutate(valid_frequence = case_when(percent < 0.04 ~ 'low',
                                     percent > min(percent)*3 ~ 'high',
                                     TRUE ~ 'valid'))

df <- df %>%
  group_by(Var1) %>% 
  filter(!any(valid_frequence=='low')) %>%
  filter(!any(valid_frequence=='high'))

```

```{r}
list <- unique(df$Var1)

clustered_songs <- clustered_songs %>%
  mutate(label= if_else(cluster %in% list, 'yes', 'no'))

```

```{r}
yes_songs <- clustered_songs %>%
  filter(label=='yes')

no_songs <- clustered_songs %>%
  filter(label=='no')

no_songs <- no_songs[sample(nrow(no_songs)),]

no_songs <- no_songs[1:nrow(yes_songs),]

labeled_songs <- bind_rows(yes_songs, no_songs)
```

```{r}
write.csv(labeled_songs, '../data/processed/labeled_songs.csv')
```